spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DevPub?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
