spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DevPub?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005